apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: 267765472985.dkr.ecr.ap-northeast-1.amazonaws.com/angular-app:latest
        ports:
        - containerPort: 80
